### PR TITLE
Update automated workflow to allow for overriding orgs for dockerhub and quay

### PR DESCRIPTION
**Pull request by detiber**
Update automated workflow to allow for overriding orgs for dockerhub and quay

### CODE REVIEW

**Comment by deitch** [comment]
@detiber a few questions:

* why do we have our own metadata action here? What does it do?
* why move the org names into secrets?

**Comment by detiber** [comment]
> @detiber a few questions:
> 
> * why do we have our own metadata action here? What does it do?

It allows to standardize a bit how we are creating the metadata and avoiding some copy-pasta type issues, since it needs to be run by multiple jobs.

> * why move the org names into secrets?

I'd rather not use a secret here TBH, but it's the only way that I could figure out how to override the value on a per-org basis, so that users can run/publish/test using their own quay/dockerhub/ghcr orgs for testing in their own forks.

Otherwise users would have to hack things up and override hardcoded values in the repo in order to override upstream quay/dockerhub orgs.

**Comment by deitch** [comment]
> I'd rather not use a secret here TBH, but it's the only way that I could figure out how to override the value on a per-org basis, so that users can run/publish/test using their own quay/dockerhub/ghcr orgs for testing in their own forks

So if I want to test the CI by launching an action manually, but pushing to a different org (not affect the official distributed supported EQXM images), then I can change the secret? But how would I do that without being admin, and doesn't it then permanently change it, so now I need an admin to put it back?

Admittedly, testing for actions is kind of miserable.

**Comment by detiber** [comment]
> > I'd rather not use a secret here TBH, but it's the only way that I could figure out how to override the value on a per-org basis, so that users can run/publish/test using their own quay/dockerhub/ghcr orgs for testing in their own forks
> 
> So if I want to test the CI by launching an action manually, but pushing to a different org (not affect the official distributed supported EQXM images), then I can change the secret? But how would I do that without being admin, and doesn't it then permanently change it, so now I need an admin to put it back?
> 
> Admittedly, testing for actions is kind of miserable.

So, basically, the secrets only exist for this repository. If a user wanted to test on their fork, they would define their own secrets there. Since their fork is under their personal account, they have admin permissions to add secrets there.

**Comment by detiber** [comment]
As a more concrete example, when testing this in my fork, I configured `DOCKER_ORG` to `detiber`, and `QUAY_ORG` to `detiber`, and that allowed me to test everything against container repos that I owned.

**Comment by deitch** [comment]
Oh, I get it. So you can test on your own fork, then open the PR when the action looks good.

There _seriously_ has to be a better way to test actions. My instinct says, "oh, just push to a local registry", but that doesn't work when CI is running on GH Actions in their runners.

I guess it looks good, then, but do you mind adding something to the docs about testing, i.e. how to do what you just described? "in your own fork, add secrets, etc."

Then we need @displague to add the necessary secrets before merging.

**Comment by detiber** [comment]
@deitch this should be ready to go now :)

**Review by deitch — APPROVED** [review]
LGTM. Still needs to wait for secrets from @displague ?

**Comment by detiber** [comment]
> LGTM. Still needs to wait for secrets from @displague ?

Nope, I updated the secrets a bit ago after @displague sent them my way.

**Comment by deitch** [comment]
Cool. Then let's do it!

**Pull request merged**
